/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import br.senai.sp.jandira.model.Especialidade;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282186
 */
public class EspecialidadeDialog extends javax.swing.JDialog {

    /**
     * Creates new form EspecialidadeDialog
     */
    public EspecialidadeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldCodigoDaEspecialidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeEspecialidade = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDescriçãoDaEspecialidade = new javax.swing.JTextField();
        buttonSalvarEspecialidade = new javax.swing.JButton();
        buttonCancelarEspecialidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 153));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(158, 168, 250));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Button-Adicionar.png"))); // NOI18N
        jLabel1.setText("   Especialidades-ADICIONAR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 370, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes de Especialidade"));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Código");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 50, 20);

        TextFieldCodigoDaEspecialidade.setEditable(false);
        TextFieldCodigoDaEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCodigoDaEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextFieldCodigoDaEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoDaEspecialidadeActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldCodigoDaEspecialidade);
        TextFieldCodigoDaEspecialidade.setBounds(30, 60, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome da Especialidade:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 110, 160, 20);

        jTextFieldNomeEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeEspecialidadeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNomeEspecialidade);
        jTextFieldNomeEspecialidade.setBounds(30, 140, 420, 30);

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setText("Descrição da especialidade:");
        jPanel2.add(jLabelDescricao);
        jLabelDescricao.setBounds(30, 190, 170, 20);

        jTextFieldDescriçãoDaEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescriçãoDaEspecialidadeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldDescriçãoDaEspecialidade);
        jTextFieldDescriçãoDaEspecialidade.setBounds(30, 220, 420, 30);

        buttonSalvarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Salvar.png"))); // NOI18N
        buttonSalvarEspecialidade.setToolTipText("Botão Salvar");
        buttonSalvarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarEspecialidadeActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSalvarEspecialidade);
        buttonSalvarEspecialidade.setBounds(690, 260, 60, 39);

        buttonCancelarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/Cancelar.png"))); // NOI18N
        buttonCancelarEspecialidade.setToolTipText("Botão Calcelar");
        jPanel2.add(buttonCancelarEspecialidade);
        buttonCancelarEspecialidade.setBounds(610, 260, 60, 39);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 770, 330);

        setSize(new java.awt.Dimension(807, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCodigoDaEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoDaEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoDaEspecialidadeActionPerformed

    private void buttonSalvarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarEspecialidadeActionPerformed
        
        //Criar um objeto especialidade
        Especialidade especialidade = new Especialidade();
        especialidade.setNome(jTextFieldNomeEspecialidade.getText());
        especialidade.setDescricao(jTextFieldDescriçãoDaEspecialidade.getText());
        
        //gravar objeto
        EspecialidadeDAO.gravar(especialidade);
        
        JOptionPane.showMessageDialog(
                this, 
                "Especialidade gravada com sucesso",
                "Especialidades",
                JOptionPane.INFORMATION_MESSAGE);
        
        //Fecha a janela
        dispose();

        
    }//GEN-LAST:event_buttonSalvarEspecialidadeActionPerformed

    private void jTextFieldDescriçãoDaEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescriçãoDaEspecialidadeActionPerformed
       
    }//GEN-LAST:event_jTextFieldDescriçãoDaEspecialidadeActionPerformed

    private void jTextFieldNomeEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeEspecialidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspecialidadeDialog dialog = new EspecialidadeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldCodigoDaEspecialidade;
    private javax.swing.JButton buttonCancelarEspecialidade;
    private javax.swing.JButton buttonSalvarEspecialidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDescriçãoDaEspecialidade;
    private javax.swing.JTextField jTextFieldNomeEspecialidade;
    // End of variables declaration//GEN-END:variables
}
